import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Calendario from "./components/Calendario";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR">
      <body
        className={`antialiased`}
      >
        <Toaster richColors position="top-right" toastOptions={{ duration: 2500 }} />

        <div className="flex h-screen">
          <div className="flex flex-col min-w-[280px] z-10 bg-blue-300 p-4 gap-4" style={{ boxShadow: "4px 0px 6px rgba(0, 0, 0, 0.45)"}}>
            <h1 className="text-2xl">Minha agenda</h1>

            <div className="h-44 w-[75%] border-2 border-gray-500 mx-auto">
              Foto aqui
            </div>

            <div className="flex flex-col gap-3 mt-5 ml-4">
              <p className="">
                Nome de usuário
              </p>
              <p className="">
                Email
              </p>
              <p className="">
                Meu telefone
              </p>
              <p className="">
                Contatos
              </p>
            </div>

            <Calendario />
          </div>

          <div className="w-full h-screen py-6 overflow-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
